version: '3.5'

networks:
  plugin-arch-server:
    name: plugin-arch-server
    external: true

services:
  app-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - APP_SECURITY_CLIENT_ID
      - APP_SECURITY_CLIENT_SECRET
      - NAMESPACE
      - LOKI_USERNAME
      - LOKI_PASSWORD
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://otel-collector:9411/api/v2/spans
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"
    networks:
      - plugin-arch-server
