version: '3.5'

networks:
  default:
  plugin-arch-server:
    name: plugin-arch-server
    external: false

services:

  envoy:
    image: envoyproxy/envoy:v1.22.5
    command: ["--service-cluster", "envoyproxy", "--config-path", "/etc/envoy/envoy.yaml"]
    ports:
      - "10000:10000"
    volumes:
      - ./compose-config/envoy.yaml:/etc/envoy/envoy.yaml
      - ./compose-config/certs/root_CA_cert.pem:/home/certs/root_CA_cert.pem
      - ./compose-config/certs/server_cert.key:/home/certs/server_cert.key
      - ./compose-config/certs/server_cert.pem:/home/certs/server_cert.pem
    networks:
      - plugin-arch-server

  grafana:
    image: grafana/grafana:9.1.6
    volumes:
      - ./compose-config/grafana-ds.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - plugin-arch-server

  jaeger:
    image: jaegertracing/all-in-one:1.37.0
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - plugin-arch-server

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./compose-config/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - plugin-arch-server

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.58.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./compose-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "9411:9411"
    depends_on:
      - tempo
      - jaeger
    networks:
      - default
      - plugin-arch-server

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./compose-config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - plugin-arch-server

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./compose-config/tempo.yaml:/etc/tempo.yaml
    networks:
      - plugin-arch-server